version: '2.0'
services:
  db:
    image: mysql:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    networks:
      - back
    environment:
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_PASSWORD: omeka

  omeka:
    depends_on:
      - db
    image: watzek/srprojects:latest
    links:
      - db
    restart: always
    networks:
      - front
      - back
    environment:
      OMEKA_DB_HOST: db:3306
      OMEKA_DB_USER: omeka
      OMEKA_DB_PASSWORD: omeka
      OMEKA_DB_NAME: omeka
      OMEKA_DB_PREFIX: _omeka
      OMEKA_DB_CHARSET: utf8
      PHP_UPLOAD_MAX_FILESIZE: 10M
      PHP_POST_MAX_SIZE: 10M
      APPLICATION_ENV: development
      VIRTUAL_HOST: srprojects.watzek.cloud
      LETSENCRYPT_HOST: srprojects.watzek.cloud
      LETSENCRYPT_EMAIL: digitalinitiatives@lclark.edu
networks:
  front:
    external: true
  back:
    external: true
